### ISSUE TITLE
6.5.2 fails to compile on FreeBSD

### ISSUE THREAD

**Issue by denningsrogue** [r-darwish/topgrade#641]
The latest version of topgrade (6.5.2)  cargo crate fails to compile on FreeBSD 12.2 RELEASE 3 and generates the following messages:

error[E0425]: cannot find function `run_apm` in module `generic`
   --> /home/denningsrogue/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-6.5.2/src/main.rs:281:51
    |
281 |     runner.execute(Step::Atom, "apm", || generic::run_apm(run_type))?;
    |                                                   ^^^^^^^ help: a function with a similar name exists: `run_gem`
    |
   ::: /home/denningsrogue/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-6.5.2/src/steps/generic.rs:59:1
    |
59  | pub fn run_gem(base_dirs: &BaseDirs, run_type: RunType) -> Result<()> {
    | --------------------------------------------------------------------- similarly named function `run_gem` defined here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: failed to compile `topgrade v6.5.2`, intermediate artifacts can be found at `/tmp/cargo-installEu0AuU`

Caused by:
  could not compile `topgrade`
